# Use the official MongoDB image as the base
FROM mongo:latest

# Set environment variables for MongoDB (optional)
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE=datawow

# Expose MongoDB default port
EXPOSE 27017